# Blog info
blog_name: lcorange
slogan: talk is cheap show me the code
url: https://www.lcorange.cn

# Set avatar (Absolute url and relative url)
avatar: /images/headimg.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: j2ee,ubuntu

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: About
    url: /about/
    target_blank: false #在新页面打开
  - name: Github
    url: https://github.com/lcnju
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 forsigner@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style:

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# Comment service
disqus_shortname:
# duoshuo_shortname: forsigner

# 不算子,文章访问量统计和显示
busuanzi: false

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "1994, Spring."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@lcnju"
    text_value_url: https://github.com/lcnju
  - type: mail
    icon: icon-mail
    text_key: QQ Mail
    text_value: "504906985@qq.com"
  - type: location
    icon: icon-location
    text_value: 苏州
